### ISSUE TITLE
Update runtimes

### ISSUE THREAD

**Issue by andreped** [EIDOSLAB/torchstain#15]
We should update the runtimes presented in the README to also cover TensorFlow (the table mentioned [here](https://github.com/EIDOSLAB/torchstain#backend-comparison)).

I would keep the `avg runtime` and remove the `total runtime` (as the latter don't add any new information). Then have `avg runtime` for all backends: Numpy, PyTorch, and TensorFlow.

**Comment by carloalbertobarbano** [comment]
Solved in https://github.com/EIDOSLAB/torchstain/commit/ece6e7c4d0ff182fc62295962a146d7e92eee2a8
