### ISSUE TITLE
Update About and tags

### ISSUE THREAD

**Issue by andreped** [EIDOSLAB/torchstain#20]
Before release it would be great if we could update the `About` and `tags` on the right-hand side in the repo. As I don't own the repo, it would be great if someone would address this.

I would have a similar description as the one described in the README (to cover all backends). I would also include the tags `tensorflow`, `numpy`, and `macenko`. Any other natural tags we should add? `digital-pathology` is a very common alternative to `computational-pathology`. Perhaps add that as well.

**Comment by carloalbertobarbano** [comment]
:+1:
