### ISSUE TITLE
Support for torch.linalg.lstsq 

### ISSUE THREAD

**Issue by raphaelattias** [EIDOSLAB/torchstain#32]
First time opening an issue, so I apologize if the approach is not correct.

I was getting an issue with pytorch 1.13, when torch.lstsq in line 52 of macenko.py for torch was replaced recently by torch.linalg.lstsq. 

Naively changing torch.lstsq to torch.linalg.lstsq would throw an error at line 106.

The correct approach is to make the following change at line 52:

`torch.lstsq(Y, HE)[0][:2]` to `torch.linalg.lstsq(HE, Y)[0]`

I will do a Pull request to solve this issue, I hope this post can help!

**Comment by andreped** [comment]
I have observed the same. Just haven't had the time to work on the pytorch stuff revently. Just note that you will need to add a fix that is backwards compatible.

Our unit tests failed on the recent PRs due to this exactly this issue. Hence, a PR would be great! :]

**Comment by raphaelattias** [comment]
Great, thank you! What's the easiest way to contribute to the repo? I have created a branch locally to solve the issue, but because of access rights, I can not push it or start a PR.

**Comment by andreped** [comment]
You have to fork the repo first, then make a branch there (ideally), and then you can make a PR.
