### ISSUE TITLE
Add Zenodo DOI

### ISSUE THREAD

**Issue by andreped** [EIDOSLAB/torchstain#9]
Following best practice, it is a good idea to make a release available on Zenodo. That way, if the GitHub repo becomes deleted or any other unforseen circumstances, people will be able to get access to the source code.

In addition, Zenodo is better for referencing purposes, as there will be a citation count. Otherwise, people will just add a URL of the repo (but which can also be fine, in some scenarios). However, as this is a tool lots of people are and will use in their research, having a separate Zenodo DOI is probably the best option, especially as this tool has not been published as part of a paper or similar.

The citation style looks like this (somewhat like any other paper):
https://github.com/andreped/GradientAccumulator#how-to-cite

And in some scenarios might also show up on Google Scholar.

However, as I am not the owner of this repo, I am unable to do so, so I suggest the maintainer(s) to look into this. Really fast to do, just remember to set the author list (with full names and not github usernames).

**Comment by carloalbertobarbano** [comment]
That is something I was thinking about as well. Zenodo seems like a good option, however I am still unsure if maybe this could become part of a publication (probably not) in the future.  I think the zenodo route would be the easisest

**Comment by andreped** [comment]
I understand. If you want it part of a publication, you are free to do so, but since the project has gotten quite popular already, and its been a while since it was made public, Zenodo is probably the way to go. But up to you :]

But I am interested in developing an improved stain normalization method in my PhD work. Integrating it into torchstain is a good option. Are you working on something similar right now? If so, we could collaborate on that task.

Nonetheless, I would still think a Zenodo DOI is a good idea.

**Comment by carloalbertobarbano** [comment]
Yes, I think Zenodo is the right way to go for the reasons you mentioned. I will work on histopathological images in the (near) future, but I don't know how much I will focus on the normalization part. 

I will link the repo to a zenodo DOI

**Comment by andreped** [comment]
> I will link the repo to a zenodo DOI

Great! I guess we are only two people contributing to this project currently? My full name is `André Pedersen`. Please, add it to the author list [here](https://github.com/EIDOSLAB/torchstain/blob/main/setup.py#L14), before making it public on Zenodo, as the repo->Zenodo is often based on the setup.py or tag release (don't recall). The e-mail you have listed is probably fine. No point in having multiple.

**Comment by carloalbertobarbano** [comment]
I fixed the authors. I think the email will just be a placeholder (people can just come to github), but if you want I can add ours. Zenodo is setup, it will generate a DOI as soon as a new release is made I think

**Comment by andreped** [comment]
This has been resolved a while back in 3bcbd7207ecd54b1263a0f6b3bc12c3cfd3113fc
